###
GET http://127.0.0.1:3000 HTTP/1.1

###
GET http://127.0.0.1:3000/coffees HTTP/1.1

###
POST http://127.0.0.1:3000/coffees HTTP/1.1
content-type: application/json

{
    "name": "coff",
    "brand": "SBUX",
    "flavor": ["chco", "cc"]
}

###
PATCH http://127.0.0.1:3000/coffees/3 HTTP/1.1
content-type: application/json

{
    "name": "coff"
}

###
DELETE http://127.0.0.1:3000/coffees/2 HTTP/1.1
